name: 'Setup jq environment'
description: 'GitHub Action to setup the `jq` command for json parsing'
author: 'urgn'

outputs:
  jq-binary:
    description: 'The binary path for the jq command'
    value: ${{ steps.install-jq.outputs.jq-binary }}
    
runs:
  using: "composite"
  steps:
    - name: Install jq
      id: install-jq
      shell: bash
      run: |
        mkdir -p ${HOME}/.local/bin
        wget https://github.com/stedolan/jq/releases/download/jq-1.7.1/jq-linux64 -O ${HOME}/.local/bin/jq
        chmod +x ${HOME}/.local/bin/jq
        echo "jq-binary=${HOME}/.local/bin/jq" >> $GITHUB_OUTPUT
